export const TEXT_STROKE = `
  -2px -2px var(--stroke-color),
  -2px -1px var(--stroke-color),
  -2px 0px var(--stroke-color),
  -2px 1px var(--stroke-color),
  -2px 2px var(--stroke-color),
  -1px -2px var(--stroke-color),
  -1px -1px var(--stroke-color),
  -1px 0px var(--stroke-color),
  -1px 1px var(--stroke-color),
  -1px 2px var(--stroke-color),
  0px -2px var(--stroke-color),
  0px -1px var(--stroke-color),
  0px 0px var(--stroke-color),
  0px 1px var(--stroke-color),
  0px 2px var(--stroke-color),
  1px -2px var(--stroke-color),
  1px -1px var(--stroke-color),
  1px 0px var(--stroke-color),
  1px 1px var(--stroke-color),
  1px 2px var(--stroke-color),
  2px -2px var(--stroke-color),
  2px -1px var(--stroke-color),
  2px 0px var(--stroke-color),
  2px 1px var(--stroke-color),
  2px 2px var(--stroke-color)
`;
